config/routes.rb
Rails.application.routes.draw do
  resources :pins
  devise_for :users
  root 'home#index'
  #root 'pins#index'
  get 'pins/index'

end

app/models/pin.rb
class Pin < ActiveRecord::Base
  belongs_to :user
  has_attached_file :image, :styles => { :medium => "300x300>", :thumb => "100x100>" }
  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :pins, dependent: :destroy # Si un usuario borra su cuenta se borran sus pins

  validates :name, presence: true, length: {in: 4..20}, uniqueness: { case_sensitive: false }

  #validates :name, presence: true, length: {in: 4..20}, uniqueness: { case_sensitive: false },
    #format: { with: /\A[a-zA-Z0-9]*\z/, message: "Solo puede contener letras y números" }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_filter :configure_permitted_parameters, if: :devise_controller?
  
  # Redirect to a determined url after log in (It modified the Devise beaviour)
  def after_sign_in_path_for(resource)
	pins_path
  end

  protected

    def configure_permitted_parameters
      devise_parameter_sanitizer.for(:sign_up) << :name
      devise_parameter_sanitizer.for(:account_update) << :name
    end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  layout "indice"

  before_action :correct_user,   only: [:edit, :update]
  #before_action :authenticate_admin!, only: [:destroy]

  def index
    @users = User.all
  end

  def about
  end

  def destroy
  end

end

app/controllers/pins_controller.rb
class PinsController < ApplicationController

  before_action :set_pin, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]
  #before_action :correct_user, only: [:edit, :update, :destroy]
  before_action :admin_or_correct, only: [:edit, :udpate, :destroy]

  # GET /pins
  # GET /pins.json
  def index
    @pins = Pin.all.order("created_at DESC").paginate(:page => params[:page], :per_page => 15)
  end

  # GET /pins/1
  # GET /pins/1.json
  def show
  end

  # GET /pins/new
  def new
    @pin = current_user.pins.build
  end

  # GET /pins/1/edit
  def edit
  end

  # POST /pins
  # POST /pins.json
  def create
    @pin = current_user.pins.build(pin_params)
     if @pin.save
      redirect_to @pin, notice: 'Pin was successfully created.'
     else
      render action: 'new'
     end
  end

  # PATCH/PUT /pins/1
  # PATCH/PUT /pins/1.json
  def update
     if @pin.update(pin_params)
      redirect_to @pin, notice: 'Pin was successfully updated.'
     else
      render action: 'edit'
     end
  end

  # DELETE /pins/1
  # DELETE /pins/1.json
  def destroy
    @pin.destroy
    redirect_to pins_path, notice: 'Pin was successfully deleted.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pin
      @pin = Pin.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pin_params
      #params.require(:pin).permit(:description, :image)
      params.require(:pin).permit(:description, :filepicker_url, :name)
    end

    def correct_user
      @pin = current_user.pins.find_by(id: params[:id])
      redirect_to pins_path, notice: "Not authorized to edit this pin" if @pin.nil?
    end

    def admin_or_correct
      #@user = User.find(params[:user_id])
      redirect_to pins_path unless administrator? ||  current_user
    end

    def administrator?
      current_user.admin?
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/pins_helper.rb
module PinsHelper
end

app/views/home/about.html.erb
<h1>About Me...</h1>
<p>My name is #{ } and I'm building a pinterest clone</p>

app/views/home/index.html.erb
<link href='https://fonts.googleapis.com/css?family=Montserrat' rel='stylesheet' type='text/css'>
<!--<link href='https://fonts.googleapis.com/css?family=Raleway' rel='stylesheet' type='text/css'>-->
 <!-- Navigation -->
 <nav class="navbar navbar-custom navbar-fixed-top" role="navigation">
   <div class="container">
     <div class="navbar-header">
       <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-main-collapse">
         <i class="fa fa-bars"></i>
       </button>
       <a class="navbar-brand page-scroll" href="#page-top">
         <i class="fa fa-play-circle"></i> <span class="light"></span> Home
       </a>
     </div>

     <!-- Collect the nav links, forms, and other content for toggling -->
     <div class="collapse navbar-collapse navbar-right navbar-main-collapse">
       <ul class="nav navbar-nav">
         <!-- Hidden li included to remove active class from about link when scrolled up past about section -->
         <li class="hidden">
           <a href="#page-top"></a>
         </li>
         <li>
           <a class="page-scroll" href="#about">Acerca de</a>
         </li>
    <li>
     <a class="page-scroll" href="#download2">Descargar CV</a>
    </li>
    <li>
     <a class="page-scroll" href="#contact2">Contacto</a>
    </li>
     <li>
      <%= link_to 'Galería', pins_path %>
     </li>
    </ul>
    </div>
<!-- /.navbar-collapse -->
</div>
<!-- /.container -->
</nav>

<!-- Intro Header -->
<header class="intro">
 <div class="intro-body">
   <div class="container">
     <div class="row">
       <div class="col-md-8 col-md-offset-2">
         <h2 class="brand-heading">Pinnacle</h2>
         <p class="intro-text"> "Tanto los sabios como los necios se vuelven arrogantes cuando reciben alabanzas."  Yamamoto Tsunetomo</p>
         <a href="#about" class="btn btn-circle page-scroll pulse">
           <i class="fa fa-angle-double-down"></i>
         </a>
       </div>
     </div>
   </div>
 </div>
</header>

<!-- About Section -->
<section id="about" class="container content-section text-center">
 <div class="row">
   <div class="col-lg-8 col-lg-offset-2">
     <h2>Acerca de</h2>
     <p>Estás viéndo una aplicación web que ha sido desarrollada con el framework  <a href="http://rubyonrails.org/">Ruby on Rails</a> basado en el lenguaje de programación interpretado <a href="https://www.ruby-lang.org/">Ruby</a>. </p>
     <p>Rails es un framework del lado del servidor que utiliza el paradigma <b>(MVC)</b> Modelo-Vista-Controlador que permite implementar un diseño más claro y un desarrollo más diferenciado y eficaz.</p>
     <p></p>
   </div>
 </div>
</section>

<!-- Download SASS Section -->
<section id="download2" class="content-section text-center">
 <div class="download-section">
   <div class="container">
     <div class="col-lg-8 col-lg-offset-2">
       <h2>Experiencia profesional</h2>
       <p>Si te interesa conocer mi andadura profesional puedes descargar mi Currículum Vitae desde el siguiente enlace:</p>
       <!--<a href="" class=" btn btn-default btn-lg">Descargar CV</a>-->
      <a href="mailto:cdsys@protonmail.com"><i class="fa fa-file-pdf-o fa-3x"></i></a>

     </div>
   </div>
 </div>
</section>

<!-- Contact Section -->
<section id="contact2" class="container content-section text-center">
 <div class="row">
   <div class="col-lg-8 col-lg-offset-2">
     <h2>Contacto</h2>
     <p>Para cualquier pregunta o si deseas asesoramiento sobre alguna cuestión informática en concreto, puedes contactar conmigo enviandome un email.  </p>

     <p>
     <!--<a href="mailto:cdsys@protonmail.com">Correo Electrónico</a> -->
     <a href="mailto:cdsys@protonmail.com"><i class="fa fa-envelope-o fa-2x"></i></a>
     <ul class="list-inline banner-social-buttons">

       <li>
        <a href="https://bitbucket.org/kalasni" target="_blank" class="btn btn-default btn-lg"><i class="fa fa-bitbucket"></i> <span class="network-name">Bbucket</span></a>
       </li>
       <li>
         <a href="https://github.com/kalasni" target="_blank" class="btn btn-default btn-lg"><i class="fa fa-github fa-fw"></i> <span class="network-name">GitHub</span></a>
       </li>
     </ul>
   </div>
 </div>
</section>


<!-- Map Section -->
<div id="map"></div>

<!-- Footer -->
<footer>
 <div class="container text-center">
   <p>Copyright &copy; Pinnacle 2016</p>
 </div>
</footer>

<!-- Google Maps API Key - Use your own API key to enable the map feature. More information on the Google Maps API can be found at https://developers.google.com/maps/ -->
<script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCRngKslUGJTlibkQ3FkfTxj3Xss1UlZDA&sensor=false"></script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Galería | Pinnacle</title>
  <%= stylesheet_link_tag   'application', 'bootstraply', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
</head>
<body class="body_bg">

  <%= render 'pins/header' %>
 <div class="container">
   <% flash.each do |name, msg| %>
    <%= content_tag(:div, msg, class: "alert alert-info") %>
   <% end %>
    <%= yield %>

  </div>
</body>
</html>

app/views/layouts/indice.html.erb
 <!DOCTYPE html>
<html>
<head>
 <title>Pinnacle | Página personal desarrollada con Ruby on Rails</title>
 <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
 <%= csrf_meta_tags %>
  <!--<%= filepicker_js_include_tag %>-->
</head>
<body id="page-top" data-spy="scroll" data-target=".navbar-fixed-top">

<%= yield %>
 <%= javascript_include_tag 'application' , 'data-turbolinks-track' => true %>
</body>
</html>

app/views/pins/_form.html.erb
<%= form_for @pin,  html: {multipart: true} do |f| %>
  <% if @pin.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@pin.errors.count, "error") %> No se ha podido guardar el pin:</h2>

      <ul>
      <% @pin.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="form-group">
    <%#= f.label :image %>
    <%= f.label :filepicker_url, "Subir imagen:" %>
    <div> <%#= f.file_field :image, class: "form-control" %>
      <%= filepicker_js_include_tag %>
      <%= f.filepicker_field :filepicker_url, button_text: "Select", button_class: "btn btn-default",
                 mimetypes:'image/*'  %>
    </div>
  </div>
  <div class="actions">
    <%= f.submit  "Create", class: 'btn btn-primary'%>
  </div>
<% end %>

app/views/pins/_header.html.erb
<link href='https://fonts.googleapis.com/css?family=Montserrat' rel='stylesheet' type='text/css'>
 <nav class="navbar navbar-default navbar_bg" role="navigation">
   <div class="container">
     <!-- Brand and toggle get grouped for better mobile display -->
     <div class="navbar-header">
       <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
              data-target="#bs-example-navbar-collapse-1">
         <span class="sr-only">Toggle navigation</span>
         <span class="icon-bar"></span>
         <span class="icon-bar"></span>
         <span class="icon-bar"></span>
       </button>
      <%= link_to 'Galería', pins_path, class: 'navbar-brand' %>
     </div>

     <!-- Collect the nav links, forms, and other content for toggling -->
     <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">

       <ul class="nav navbar-nav navbar-right">

         <li><%= link_to 'Home', root_path %></li>
         <li><%= link_to "Mostrar Pins", pins_path %></li>

          <% if user_signed_in? %>
            <li><%= link_to current_user.name, edit_user_registration_path %></li>
            <li><%= link_to 'Añadir Pin', new_pin_path %></li>
            <li><%= link_to 'Salir', destroy_user_session_path, method: :delete %></li>
            <%# if current_user.admin? %>
            <!--<li><%#= link_to 'Usuarios', home_index_path %></li>-->
            <%# end %>
          <% else %>
            <li><%= link_to "Entrar", new_user_session_path %></li>
            <li><%= link_to "Registrarse", new_user_registration_path %></li>
          <% end %>
       </ul>

     </div><!-- /.navbar-collapse -->
   </div><!-- /.container-fluid -->
 </nav>

app/views/pins/edit.html.erb
<div class="panel panel-default">
  <div class="panel-heading"><h2>Editar Pin</h2></div>
  <div class="panel-body">

    <%= render 'form' %>

    <%= link_to 'Mostrar', @pin %> |
    <%= link_to 'Volver', pins_path %>

  </div>
</div>

app/views/pins/index.html.erb
<!-- Hay que cargarlo al principio para que se incluya antes del contenido del body -->
<%= javascript_include_tag 'bootstrap-waterfall' %>
<script>
  $(document).ready(function () {
        $('#waterfall-container').waterfall();
  });
</script>

 <div id="waterfall-container" class="transitions-enabled">
   <% @pins.each do |pin| %>
   <div class="box">
     <div class="panel panel-default">

       <%#= link_to image_tag(pin.image.url(:medium)), pin, class: 'img-responsive' %>
       <%= link_to (filepicker_image_tag pin.filepicker_url, w: 300, h: 300, fit: 'clip'), pin %><br/>

       <div class="panel-body">
         <%= truncate(pin.description, length:20) { link_to "Ver más", pin, class: "lik"}%><br/>
         <span class="has-tooltip" data-toggle="tooltip" title="<%= "Created on #{pin.created_at.strftime("%d/%m/%Y at %w:%M %p")}" %>">
          <strong><%= pin.user.name if pin.user %> </strong>
        </span><br/>
      </div> <!-- div panel-body -->

      <% if pin.user == current_user  ||  current_user.try(:admin?) %>

      <div class="panel-footer">
       <%= link_to 'Editar', edit_pin_path(pin) %><br/>
       <%= link_to 'Borrar', pin, method: :delete, data: { confirm: '¿Estás seguro?' } %>
     </div>

     <% end %>
   </div> <!-- div panel panel-default -->
   </div>  <!-- div box -->
 <% end %>
</div>
</div> <!-- div -->
<div class="center">
 <%= will_paginate @pins, renderer: BootstrapPagination::Rails %>
</div>

app/views/pins/new.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <h2>Nuevo Pin</h2>
  </div>
  <div class="panel-body">

    <%= render 'form' %><br>
    <%= link_to 'Volver', pins_path, class: 'lik' %>

  </div>
</div>

app/views/pins/show.html.erb
<div class="row">
  <div class="col-md-offset-2 col-md-8">
    <div class="panel panel-default">
      <div class="panel-heading center">
        <%#= image_tag @pin.image.url(:medium), class: 'img-responsive' %>
        <%= filepicker_image_tag @pin.filepicker_url, w: 500, h: 500, fit: 'clip' %>
      </div>
      <div class="panel-body">
        <%= @pin.description %><br/>
        <strong><br/><%= @pin.user.name %></strong><br/>
        <i><%= @pin.user.updated_at.strftime("%d/%m/%Y at %w:%M %p") %></i><br/>

        <% if @pin.user == current_user %>
          <%= link_to 'Editar', edit_pin_path(@pin), class: 'lik' %> |
        <% end %>
        <%= link_to 'Volver', pins_path(@pin), class: 'lik' %>
      </div>
    </div>
  </div>
</div>